#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit "${1}" || {
  printf "\n\033[1;31m[Commit Message Failed]\033[0m 若需跳過檢核強行提交，請下：\033[1;36mgit commit --no-verify\033[0m\n\n"
  exit 1
}

